--- Data Cleaning steps
---		1. Convert date column from varchar to date type
---		2. Remove ',' from the numbers and convert the numeric columns data type to integer
---		3. Store the result in a CTE for further processing

 WITH CA_HOMELESS_CLEANED_TABLE AS
	(SELECT CAST(date AS date),
			COUNTY,
			CAST(REPLACE(ROOMS_AVAILABLE,',','') AS integer) AS ROOMS_AVAILABLE,
			CAST(REPLACE(ROOMS_REQUESTED,

									',',
									'') AS integer) AS ROOMS_REQUESTED,
			CAST(REPLACE(TRAILERS_REQUESTED,

									',',
									'') AS integer) AS TRAILERS_REQUESTED,
			CAST(REPLACE(TRAILERS_DELIVERED,

									',',
									'') AS integer) AS TRAILERS_DELIVERED,
			CAST(REPLACE(DONATED_TRAILERS_DELIVERED,

									',',
									'') AS integer) AS DONATED_TRAILERS_DELIVERED
		FROM COVID_CA_HOMELESS_IMPACT),
		
--- Taking cleaned data and then aggregating it

	AGGREGATED_DATA AS
	(SELECT EXTRACT(MONTH FROM date) AS MM,
			EXTRACT(YEAR FROM date) AS YY,
			COUNTY,
			SUM(ROOMS_AVAILABLE) AS ROOMS_AVAILABLE,
			SUM(ROOMS_REQUESTED) AS ROOMS_REQUESTED,
			SUM(TRAILERS_REQUESTED) AS TRAILERS_REQUESTED,
			SUM(TRAILERS_DELIVERED) AS TRAILERS_DELIVERED,
			SUM(DONATED_TRAILERS_DELIVERED) AS DONATED_TRAILERS_DELIVERED
		FROM CA_HOMELESS_CLEANED_TABLE
		GROUP BY 1,2,
			3
		ORDER BY 2,1) 
		
--- Finding County with maximum rooms_requested each year --

SELECT YY,
	COUNTY
FROM
	(SELECT YY,
			COUNTY,
			SUM(COALESCE(ROOMS_AVAILABLE,0)),
			ROW_NUMBER() OVER (PARTITION BY YY ORDER BY SUM(COALESCE(ROOMS_AVAILABLE,0)) DESC) AS ROOM_AVL_RANK
		FROM AGGREGATED_DATA
		GROUP BY YY,
			COUNTY) A1
WHERE ROOM_AVL_RANK = 1;

--- Finding County with maximum rooms_requested each year --

SELECT YY,
	COUNTY
FROM
	(SELECT YY,
			COUNTY,
			SUM(COALESCE(ROOMS_REQUESTED,0)),
			ROW_NUMBER() OVER (PARTITION BY YY ORDER BY SUM(COALESCE(ROOMS_REQUESTED,0)) DESC) AS ROOM_AVL_RANK
		FROM AGGREGATED_DATA
		GROUP BY YY,
			COUNTY) A1
WHERE ROOM_AVL_RANK = 1;

-- Finding County with maximum trailers_requested each year --

SELECT YY,
	COUNTY
FROM
	(SELECT YY,
			COUNTY,
			SUM(COALESCE(TRAILERS_REQUESTED,0)),
			ROW_NUMBER() OVER (PARTITION BY YY ORDER BY SUM(COALESCE(TRAILERS_REQUESTED,0)) DESC) AS ROOM_AVL_RANK
		FROM AGGREGATED_DATA
		GROUP BY YY,
			COUNTY) A1
WHERE ROOM_AVL_RANK = 1;

-- Finding County with maximum trailers_delivered each year --

SELECT YY,
	COUNTY
FROM
	(SELECT YY,
			COUNTY,
			SUM(COALESCE(TRAILERS_AVAILABLE,0)),
			ROW_NUMBER() OVER (PARTITION BY YY ORDER BY SUM(COALESCE(TRAILERS_AVAILABLE,0)) DESC) AS ROOM_AVL_RANK
		FROM AGGREGATED_DATA
		GROUP BY YY,
			COUNTY) A1
WHERE ROOM_AVL_RANK = 1;
